### ISSUE TITLE
Interrupt handling performance

### ISSUE THREAD

**Issue by mfld-fr** [mfld-fr/sys86#2]
Comment from @ghaerr in #1 : pushing the caller context on the kernel stack rather than on the user stack brings simplicity in accessing the system call context and in task switching, at the cost of requiring more space in the kernel data segment.

Use case & requirement : serial port input - minimal latency between the interrupt signal and reading the 'received data' register to sustain maximum input data rate.
  
Proposal : use the SBC high resolution timer T1 @ 5 MHz to measure the time between the interrupt handler entry and the end of the 'received data' register read in `serial_proc`, and then the time to exit the interrupt handler. Benchmark both options : 'push context on user / kernel stack' and 'push context on kernel stack only'.

**Comment by ghaerr** [comment]
> use the SBC high resolution timer T1 @ 5 MHz to measure the delay between the interrupt handler entry and the end of the 'received data' register read in serial_proc

Have you ever heard of Michael Abrash? This guy is great and wrote a fantastic book on x86 issues, which covers topics I'm sure you'll be interested in. Here's his version of a "perfect timer", which he designed to be extremely accurate. Check out what he has to say about precise timing: http://www.jagregory.com/abrash-black-book/#the-zen-timer.  If you end up using this, I would be very interested in having such a facility for ELKS also, especially as a macro.

> Use case & requirement : serial port input - minimal latency between the interrupt signal and reading the 'received data' register to sustain maximum input data rate.

I wasn't aware this was another requirement. Sustained max input really requires a minimal interrupt-to-interrupt time, not minimal latency to interrupt, as there is still time to read the receive register, even on a single-buffered chip, while the next received character is being shifted into the receive holding register. I ended up writing a completely separate "fast" interrupt handler with no stack switching in ELKS to get around what I perceived was too much system overhead in the areas we're discussing. In retrospect, it only mattered at very high baud rates, above 38400 baud, on very slow systems. Otherwise, the kernel overhead is acceptable.

Have you read much about Linux's "top" and "bottom half" interrupt design? I'm not a big fan of it, but it separates the top half of an interrupt handler getting in and out extremely quickly while scheduling a special bottom-half completion routine run after the interrupt in kernel mode, which solves the problem for them.

**Comment by mfld-fr** [comment]
Added basic time sampling in 0788502. Path from interrupt entry to register reading in `serial_proc()` is quite fast, but not the path to exit the interrupt: `82 1B4`

**Comment by mfld-fr** [comment]
Several optimizations in eab83f5.

Before compiler optimization: `82 194 86`
After compiler optimization: `66 EB 55`

**Comment by mfld-fr** [comment]
Now having a full timed chain "interrupt -> first task -> second task", so including both asynchronous and synchonous task switching.

Before the wait object: `66 113 3B D2 70`
After the wait object: `66 F3 3B B8 56`

Can fork now into two competing branches that differ only by:
- `user`: user mode context pushed on the user stack
- `kern`: user mode context pushed on the kernel stack

**Comment by mfld-fr** [comment]
Now doing timing on **real SBC**, not in EMU86 anymore.

Hexadecimal values below are in 0.2 microsecond units.
Each line is the average of 5 samples.

Branch `kern`:
commit efea65e: `199 410 10A 30F 170`

Branch `user`:
commit 795ad1e: `1A0 424 109 313 1AF`

**Comment by mfld-fr** [comment]
Timings with idle task in user space (user to kernel transition on serial interrupt):

Branch `kern`:
commit dce7970: `1DC 436 10D 324 17D`

Branch `user`: (after removing dummy SP)
commit 98a2885: `1B7 442 10C 321 17C`

**Comment by mfld-fr** [comment]
@ghaerr : So now we can conclude after this benchmark.

Option 'user' has 305.8 usecs between each serial interrupt from user mode, while option 'kern' has 310.8 usecs. Not a big difference (- 1.6%). In both options the timing is secure for 9600 bauds (~ 1 msec), but with limited margin for 19200 bauds (~500 msec).

Option 'kern' makes access to system call registers easier (near pointer), saves 6 bytes in each task structure, but costs 20 more bytes in each kernel stack, while option 'user' put that bytes in each user stack, so saves more kernel space. No option secures the user stack (both push some registers on that stack).

Timings in kernel task switching are equivalent, code is a bit more complex for option 'kern' to build the initial stacks.

Design choice is therefore not as obvious as you stated.

**Comment by ghaerr** [comment]
Hello @mfld-fr,

Here are my thoughts:

> Option 'user' has 305.8 usecs between each serial interrupt from user mode, while option 'kern' has 310.8 usecs. Not a big difference (- 1.6%). In both options the timing is secure for 9600 bauds (~ 1 msec), but with limited margin for 19200 bauds (~500 msec).

Interesting to know, no appreciable difference in design for hardware processing.



> Option 'kern' makes access to system call registers easier (near pointer), saves 6 bytes in each task structure, but costs 20 more bytes in each kernel stack, while option 'user' put that bytes in each user stack, so saves more kernel space. No option secures the user stack (both push some registers on that stack).

If running in tiny space with very limited RAM (< 1k bytes), reserving extra space for elegant design would not be worth it. For larger systems, more approaching UNIX/Linux/ELKS, a 20 byte kernel stack difference out of a necessary 512+ bytes each is a very small price to pay for a much more elegant design.  When it comes time to implement signals, you will understand why saving registers on the user stack cost dearly, for instance.


> Timings in kernel task switching are equivalent, code is a bit more complex for option 'kern' to build the initial stacks.

Good to know no difference in task switching times.


> Design choice is therefore not as obvious as you stated.

Obviously, form follows function, and what the system is built to accomplish dictates a large variety of possible design choices. My previous statements were relating to requirements of a multiprocessing system like early UNIX/Linux/ELKS with features including lots of system calls, signals, ease of writing device drivers, provable system correctness and an elegant, highly structured low-level multitasking design. I am not familiar with what the requirements are for the system you are designing, my apologies.

One other thing: kernel vs user mode doesn't really mean much on an 8086, where the hardware doesn't require a narrow design path for handling user-to-kernel mode transitions on interrupts. Thus, exactly how context is saved or how tasking is implemented doesn't constrain external hardware device handling nearly as much, since an interrupt routine can always be written completely outside of a given kernel design, which isn't possible on protected mode systems.

Thank you!

**Comment by mfld-fr** [comment]
@ghaerr : Thanks for your comments. I will continue on the `kern` option as it looks like easier for implementing system calls, but I keep the `user` option until I can compare the cost of implementing signals in both.
